### PR TITLE
Add support for using es6/es7 features with Babel.

### PR DESCRIPTION
**Pull request by tkh44**
Nothing new is required of end user.  Conversion happens on run.

### CODE REVIEW

**Comment by umaar** [comment]
@kolodny What do you think about this? Could be quite nice to complete exercises using modern ES features.

**Comment by kolodny** [comment]
It looks good, I've been meaning to getting around and testing this

**Comment by alvaropinot** [comment]
nice idea to think forward modern ES :D

**Comment by kolodny** [comment]
I'm nuking this considering that node 7 is pretty much covers [97% of es6](http://kangax.github.io/compat-table/es6/#node7)

I apologize for not being more on top of this PR

**Pull request closed without merging**
