### PR TITLE
Add 'once ' challenge.

### PR DESCRIPTION
**Pull request by trexnix**
Hi, 

I would like to add `once` to the list. It is an easy challenge (slightly easier than `debounce`).

http://underscorejs.org/#once

### CODE REVIEW

**Comment by kolodny** [comment]
Nice, thanks

**Comment by trexnix** [comment]
I'll add solution for this after you merge `master` branch into `solutions` one. One question, do I have to wait for that? Or I just do it myself, add solution file and create another pull request to `solutions` branch? This is my first commit by the way. Thanks in advanced.

**Comment by kolodny** [comment]
It's already merged into master, the solutions branch is kinda my solutions so there really shouldn't be any PR to it

**Comment by trexnix** [comment]
I got it.

**Pull request merged**
