### PR TITLE
Fix 'throttle' a proper timeout of the 'will execute every threshold …

### PR DESCRIPTION
**Pull request by 2hu12**
Fix 'throttle' a proper timeout of the 'will execute every threshold ms' test case.

### CODE REVIEW

**Comment by kolodny** [comment]
Yup, there was a race condition, thanks

**Comment by kolodny** [comment]
@rnsloan does this fix your throttle solution?

**Comment by rnsloan** [comment]
@kolodny I have tested the solution provided in the `solutions` branch against the latest test (with the `clock.tick` additions) and it is now passing in my environment: iojs v2.2.1 .

**Comment by rnsloan** [comment]
@kolodny as an aside, I have noticed that underscore's throttle method fails this test in my environment around 20%-30% of the time

```
1) throttle will execute every threshold ms:

      AssertionError: [ 0, 10, 21, 32, 43, 54 ] deepEqual [ 0, 11, 22, 33, 44, 55 ]
      + expected - actual

       [
         0
      -  10
      -  21
      -  32
      -  43
      -  54
      -  65
      +  11
      +  22
      +  33
      +  44
      +  55
       ]
```

**Comment by kolodny** [comment]
hmm, maybe I should allow a fudge factor then

**Pull request merged**
