### PR TITLE
Added flatten

### PR DESCRIPTION
**Pull request by trexnix**
Hi @kolodny , I added a new challenge. Creating a function named `flatten` that can flattens a nested array.

### CODE REVIEW

**Comment by danrevah** [comment]
+1 
nice challenge

**Comment by trexnix** [comment]
Thanks. This one is interesting :).

**Comment by kolodny** [comment]
Looks awesome, can you make it so that you don't need to pass in true for it to be recursive? I'll merge it in then.

Great challenge BTW, Thanks!

**Comment by danrevah** [comment]
@kolodny I don't think he needs to change it.. 
underscorejs: http://underscorejs.org/#flatten

**Comment by kolodny** [comment]
@danrevah while true, these exercises are for the challenge/learning experience, not to reimplement underscore one method at a time :wink:

**Comment by danrevah** [comment]
that's also true, but with the shallow flag it could be a bit more complex, and in my opinion that's the whole point :)

**Comment by trexnix** [comment]
No problem, check it out again.

**Comment by kolodny** [comment]
@trexnix @danrevah Sorry, I wasn't clear. I meant that just the recursive aspect is enough for the test, no need for the shallow part. The challenge is to think recursively for this, if someone can solve it for that case then the shallow case is trivial

**Comment by kolodny** [comment]
Awesome, thanks!

**Pull request merged**
